---
apiVersion: v1
kind: Pod
metadata:
  name: cat-1
  namespace: network-tools
  labels:
    app: network-tools
    instance: cat-1
spec:
  hostNetwork: false
  hostPID: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    kubernetes.io/hostname: ocp-sno1p1
  containers:
  - name: network-tools
    image: quay.io/midu/network-tools:latest
    imagePullPolicy: Always
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: 512Mi
    volumeMounts:
    - name: pcaps
      mountPath: /data/pcaps
  volumes:
  - name: pcaps
    emptyDir: {}
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: cat-2
  namespace: network-tools
  labels:
    app: network-tools
    instance: cat-2
spec:
  hostNetwork: false
  hostPID: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    kubernetes.io/hostname: ocp-sno1
  containers:
  - name: network-tools
    image: quay.io/midu/network-tools:latest
    imagePullPolicy: Always
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: 512Mi
    volumeMounts:
    - name: pcaps
      mountPath: /data/pcaps
  volumes:
  - name: pcaps
    emptyDir: {}
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: cat-3
  namespace: network-tools
  labels:
    app: network-tools
    instance: cat-3
spec:
  hostNetwork: false
  hostPID: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    kubernetes.io/hostname: ocp-sno1p1
  containers:
  - name: network-tools
    image: quay.io/midu/network-tools:latest
    imagePullPolicy: Always
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_ADMIN
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: 512Mi
    volumeMounts:
    - name: pcaps
      mountPath: /data/pcaps
  volumes:
  - name: pcaps
    emptyDir: {}
  restartPolicy: Always
