---
apiVersion: v1
kind: Pod
metadata:
  name: perf-pod
  namespace: network-tools
  labels:
    app: perf-tools
spec:
  hostNetwork: false
  hostPID: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    kubernetes.io/hostname: ocp-sno1
  containers:
  - name: perf-tools
    image: quay.io/midu/perf-tools:latest
    imagePullPolicy: Always
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "500m"
        memory: 512Mi
  restartPolicy: Always
