---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  name: sno1p1
  namespace: sno1
data:
  username: "YWRtaW4="
  password: "YWRtaW4="
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "60"
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "ocp-sno1p1"
    bmac.agent-install.openshift.io/role: "worker"
  name: sno1p1
  namespace: sno1
  labels:
    infraenvs.agent-install.openshift.io: "sno1p1"
spec:
  online: true
  bootMACAddress: "AA:AA:AA:AA:02:02"
  automatedCleaningMode: disabled
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    address: redfish-virtualmedia://172.16.30.2:9000/redfish/v1/Systems/local/sno1p1
    credentialsName: sno1
    disableCertificateVerification: true
